export const SEARCH_ACTIONS = {
  SET_SEARCH_FIELD: 'SET_SEARCH_FIELD',
  SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
  ADD_SEARCH_FIELD: 'ADD_SEARCH_FIELD',
  DELETE_SEARCH_FIELD: 'DELETE_SEARCH_FIELD',
  ADD_SEARCH_QUERY: 'ADD_SEARCH_QUERY',
  DELETE_SEARCH_QUERY: 'DELETE_SEARCH_QUERY',
};